name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  milliseconds:
    description: 'number of milliseconds to wait'
    required: true
    default: '1000'
runs:
  using: 'node12'
  main: 'dist/index.js'
